### ISSUE TITLE
collect ansible_facts or ignore variables that use it

### ISSUE THREAD

**Issue by jjblack** [RebelCodeBase/testaid#1]
I have some variables in my playbooks that rely on the version of the host. For example, if I have in default/main.yml:
```
file: "{{ (ansible_facts['distribution_version'] is version('18.04', '>=')) |  ternary('foo', 'bar')}}"
```

Then when I call `testvars` in a testfile with
```
file_name = testvars['file']
```
the following error is raised
```
testvars = {'file': "An unhandled exception occurred while templating '[\"{{ (ansible_facts['distribution_version'] is version('18.04', '>=')) |  ternary('foo', 'bar')}}\"]'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Version comparison: 'dict object' has no attribute 'distribution_version'"}
```

The testinfra ansible module [host.ansible.get_variables()](https://testinfra.readthedocs.io/en/latest/modules.html#testinfra.modules.ansible.Ansible) just reports this variable as the literal `{{ (ansible_facts['distribution_version'] is version('18.04', '>=')) |  ternary('foo', 'bar')}}`. But this is also unusable to me.

I already only run certain tests on specific versions. So I don't mind manually declaring `foo` and `bar` in different tasks. So is there a way to ignore the variables that cause this failure? Or maybe only throw the error if I call that variable (it throws a failure in each test that I call `testvars`)? Perhaps there is a way to use the testinfra ansible module to run a setup task that collects `ansible_facts` and then there would be no need to ignore these errors.

**Comment by RebelCodeBase** [comment]
Hello jjblack, thanks a lot for your feedback! 

I've added a method to testaid v0.5 that adds ansible_facts to testvars by calling the ansible setup module.

Could you please try if this solves your problem?

**Comment by RebelCodeBase** [comment]
I've investigated this further and unfortunately the answer to my question is: no, this does not solve your problem. There are two problems here:

1. testaid does not use molecule and does not run `ansible-playbook`. Instead it uses testinfra to run `ansible` ad-hoc commands. So it uses the ansible setup module to gather facts and not `gather_facts: true` in an ansible playbook. But the result is different:

(some) `ansible_facts` via ansible [debug](https://docs.ansible.com/ansible/latest/modules/debug_module.html) module gathered by `gather_facts:true` in a molecule `ansible-playbook` run:
```
"distribution_file_variety": "Debian",
"distribution_major_version": "10",
"distribution_release": "buster",
"distribution_version": "10",
```

(some) `ansible_facts` via (setup)[https://docs.ansible.com/ansible/latest/modules/setup_module.html] module in a testinfra `ansible` run:
```
"ansible_distribution_file_variety": "Debian",
"ansible_distribution_major_version": "10",
"ansible_distribution_release": "buster",
"ansible_distribution_version": "10",
````
I consider this an ansible bug!

2. In order to inject `ansible_facts` to the debug module the testinfra maintainers need to accept my (pull request)[https://github.com/philpep/testinfra/pull/462]. Or you have to patch testinfra yourself.

**Comment by piroux** [comment]
Why was it not possible to use the [VariableManager](https://github.com/ansible/ansible/blob/93ea9612057d47b28c9c42d439ef5679351b762b/lib/ansible/vars/manager.py#L74) from ansible to force the same behaviour to load the variables ?

**Comment by RebelCodeBase** [comment]
The first, most obvious and slightly embarrassing answer is: I didn't know about the VariableManager until you've pointed it out to me. There even is an official [hands-on example](https://docs.ansible.com/ansible/latest/dev_guide/developing_api.html) on how to use it! So probably I have to think about rewriting the whole plugin and use the python API instead.

**Comment by RebelCodeBase** [comment]
So five days later I've come up with a solution: I've rewritten most of the plugin. From version 0.7 it uses the Ansible Python API (see [README](/RebelCodeBase/testaid/blob/master/README.rst)). So the tests above should pass by now and I am looking forward to your feedback.

One more effect of the rewrite: testaid does not use the host fixture of testinfra any more so I was able to change the scope of the fixtures to 'session'. This means that pytest will cache the testvars by default and you only need the pytest cache plugin if you want to cache in between test runs.

Oh and I've written a "playbook api" fixture called moleculebook which can be used to run ansible playbooks programmatically against a molecule host. Happy testing!
