### ISSUE TITLE
Buggy handling of TESTVARS_ROLES_WHITELIST en var

### ISSUE THREAD

**Issue by piroux** [RebelCodeBase/testaid#8]
I just tried the white-listing role feature you added this week.
I have been caught by one thing which was not specified in the `README.md`: 

> List of roles separated by colon

Indeed, from the code in plugin.py, it seems that each "role", comprising the list of roles passed to the environment variables TESTVARS_ROLES_*, should be the path of the role.

Moreover there is a bug because a Python Path cannot be splitted with `split`.

```
    molecule_scenario_directory = PosixPath('***/testaid/test/system/debian/roles/roleinclusion-simple/molecule/default')
    
        @pytest.fixture(scope='session')
        def testvars_roles_whitelist(molecule_scenario_directory):
            '''environment variable TESTVARS_ROLES_WHITELIST'''
            try:
                whitelist = Path(os.environ['TESTVARS_ROLES_WHITELIST'])
            except KeyError:
                return list()
    >       return whitelist.split(':')
    E       AttributeError: 'PosixPath' object has no attribute 'split'
    
    /home/piroux/.local/share/virtualenvs/testaid-s4mU2IlU/lib/python3.6/site-packages/testaid/plugin.py:133: AttributeError
```

**Comment by RebelCodeBase** [comment]
Yes, I admit: I did not yet write tests for this as I don't know how to write unit tests. But I will write system tests now.

First, I wanted to treat the new environment variables as paths (that's why I created the PathList class in the first place). But then I thought again and what we really want are names of roles here not paths to roles, right? So I will write system tests now which will fail and then I'll fix this bug.
